builds:
- id: "kcp"
  main: ./cmd/kcp
  binary: bin/kcp
  ldflags:
  - "{{ .Env.LDFLAGS }}"
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  - ppc64le
  ignore:
  - goos: darwin
    goarch: ppc64le
  env:
  - CGO_ENABLED=0
- id: "kubectl-kcp"
  main: ./cmd/kubectl-kcp
  binary: bin/kubectl-kcp
  ldflags:
  - "{{ .Env.LDFLAGS }}"
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  - ppc64le
  ignore:
  - goos: darwin
    goarch: ppc64le
  - goos: windows
    goarch: ppc64le
  env:
  - CGO_ENABLED=0
- id: "kubectl-workspace"
  main: ./cmd/kubectl-workspace
  binary: bin/kubectl-workspace
  ldflags:
  - "{{ .Env.LDFLAGS }}"
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  - ppc64le
  ignore:
  - goos: darwin
    goarch: ppc64le
  - goos: windows
    goarch: ppc64le
  hooks:
    post:
      - ln -sfr bin/kubectl-workspace bin/kubectl-workspaces
      - ln -sfr bin/kubectl-workspace bin/kubectl-ws
  env:
  - CGO_ENABLED=0
archives:
- id: kcp
  builds:
  - kcp
- id: kubectl-kcp-plugin
  builds:
  - kubectl-kcp
  - kubectl-workspace
  name_template: "kubectl-kcp-plugin_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  files:
    - bin/kubectl-workspaces
    - bin/kubectl-ws
release:
  draft: true
  prerelease: auto
  mode: keep-existing
